use Logistics_Analytics;

--1. What is the total revenue generated by the company over the three-year period?

select * from loads
select ROUND(sum(revenue)/1000000,2) as total_revenue from loads

--2.How many total shipments were completed?
SELECT count(load_id) as total_loads from loads

--3. What is the average revenue earned per shipment?
SELECT ROUND(AVG(revenue),2) as avg_revenue from loads;

--4. How many unique customers placed shipments?
SELECT * FROM customers;
SELECT * FROM loads;

SELECT l.customer_id, c.customer_name, COUNT(l.customer_id) as total_loads
FROM loads l
JOIN customers c
on l.customer_id = c.customer_id
group by l.customer_id, c.customer_name

--5. What is the yearly revenue trend (2022, 2023, 2024)
SELECT YEAR(load_date) as years, 
		ROUND(sum(revenue),2) as total_revenue 
from loads
group by YEAR(load_date);

--6. How many shipments were completed each year?
SELECT YEAR(load_date) as years, 
		Count(load_date) as total_loads
from loads
group by YEAR(load_date);

--7. Which year generated the highest revenue?
SELECT top 1 YEAR(load_date) as years, 
		ROUND(sum(revenue),2) as total_revenue 
from loads
group by YEAR(load_date)
order by total_revenue desc;

--8. Top 10 customers by revenue
SELECT * FROM customers;
SELECT * FROM loads;

SELECT TOP 10 
		l.customer_id, c.customer_name, 
		ROUND(SUM(revenue),2) as total_revenue
FROM loads l
JOIN customers c
ON l.customer_id = c.customer_id
GROUP BY l.customer_id, c.customer_name
ORDER BY total_revenue desc


--9. Top customers by shipment count
SELECT TOP 10 
		l.customer_id, c.customer_name, 
		COUNT(l.customer_id) as total_loads
FROM loads l
JOIN customers c
ON l.customer_id = c.customer_id
GROUP BY l.customer_id, c.customer_name
ORDER BY total_loads desc

--10. Revenue by customer type
SELECT 
	c.customer_type as customer_type,
	ROUND(sum(revenue),2)
from customers c
JOIN loads l
ON c.customer_id = l.customer_id
GROUP BY c.customer_type

--11. Revenue by freight type
SELECT 
	c.primary_freight_type as freight_type,
	ROUND(sum(revenue)/1000000,2)
from customers c
JOIN loads l
ON c.customer_id = l.customer_id
GROUP BY c.primary_freight_type

--12. Active vs Inactive customer revenue
SELECT 
	c.account_status,
	ROUND(sum(revenue),2)
from customers c
JOIN loads l
ON c.customer_id = l.customer_id
GROUP BY c.account_status


--13. Customer lifetime value
SELECT 
	customer_id, 
	ROUND(SUM(revenue),2)  as total_revenue
from loads
group by customer_id
order by total_revenue desc

--14. Most profitable route
SELECT  
	r.route_id, r.origin_city, r.destination_city,
	ROUND(sum(l.revenue),2) as total_revenue
FROM Routes r
JOIN Loads l
ON 
	l.route_id = r.route_id
GROUP BY r.route_id, r.origin_city, r.destination_city
ORDER BY total_revenue desc

--15. Longest routes
SELECT top 5 route_id, origin_city, destination_city,
typical_distance_miles
FROM Routes 

GROUP BY route_id, origin_city, destination_city, typical_distance_miles
ORDER BY typical_distance_miles DESC

--16. Revenue per mile

--17. Average revenue by transit days
SELECT r.typical_transit_days,
	ROUND(AVG(l.revenue),2) as avg_revenue
FROM routes r
JOIN loads l
ON r.route_id = l.route_id
GROUP by r.typical_transit_days

--18. Distance vs Revenue
SELECT 
	r. typical_distance_miles,
	ROUND(SUM(l.revenue),2) as total_revenue
FROM Routes r
JOIN loads l
ON r.route_id = l.route_id
GROUP BY r.typical_distance_miles

select * from loads